version: "3"

services:
  app:
    build:
      context: .
    image: &app app
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=db
    command: >
      sh -c "python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6385:6379"

  db:
    image: postgres:12-alpine
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
